### ISSUE TITLE
Vest not loading 

### ISSUE THREAD

**Issue by MatthewLane15** [RealDebugg/RPH-ClothingToggle#1]
Hello after removing the vest it will not return. i have tried with all my vests and they all don't work.

**Comment by RealDebugg** [comment]
Appreciate the bug report however I need some more info. Is this happening to any other clothing items? If so, what are the IDs of the EUP items that it is happening to? and what is the ID of the vest eup item you were using?

**Comment by MatthewLane15** [comment]
Hi i have used the basic EUP vests and hannako's (all vest and items under armor)and they do not work. this also occurs with any bag/parachute/mask. 

all other clothing items work. 

EDIT: 
it doesn't show that the vest was added in the EUP menu so it is not a texture issue.

**Comment by RealDebugg** [comment]
Appreciate the details. I will have a look into this during the weekend, if I need anything else I’ll comment on it and ask for it here. Try keeping yourself up to date until the ticket closes!

**Comment by MatthewLane15** [comment]
Thanks will do. It is an amazing idea just has some bugs

**Comment by RealDebugg** [comment]
Follow up question, the EUP you're using is it addon or replacements?

**Comment by MatthewLane15** [comment]
i have tried it with both. it doesn't work

**Comment by MatthewLane15** [comment]
> i have tried it with both. it doesn't work

just a little more context. i have used both the base EUP vests that come with the install and some addon vests but neither work

**Comment by RealDebugg** [comment]
Alrighty, awesome and thanks for the quick response. This will help a lot! Unfortunately due to scripthook not having been updated yet I might have to delay testing, if I can't figure it out by going through the code it might take longer to get a fix out but I will keep you updated on here.

**Comment by MatthewLane15** [comment]
Thanks! glad i could help.

**Comment by RealDebugg** [comment]
The issue has been resolved and will be patched with an update coming today. Keep up to date with releases in the releases tab, LSPDFR or on my discord server: https://discord.gg/Zng4BaU4f7
