### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by Echooo29** [RealDebugg/RPH-ClothingToggle#2]
Add a "modifier" key that you have to press at the same time as the quick keybind for gloves and glasses to avoid conflicts with other keybinds. You could also add an optional feature in the .ini that makes it so that the quick keybinds for gloves and glasses only work while outside of a vehicle, to avoid further conflicts with keybinds.

**Comment by RealDebugg** [comment]
Has now been added to the Trello and will be added in with the next update, for the time being I would remap both buttons to something either unusable or that isn't conflicting

**Comment by RealDebugg** [comment]
Added in version 2.5.0 :)
