### ISSUE TITLE
Mask doean't change to what i want it to change

### ISSUE THREAD

**Issue by Andy55596** [RealDebugg/RPH-ClothingToggle#3]
I added mMask=7 to change the body cam but when I toggle Mask it just disappears doesn't change to slot 7 or whatever number i put in.

**Comment by RealDebugg** [comment]
mMask is not an option in the settings file. The mask toggle button only toggles between removing the "mask" and putting it back on.

**Comment by Andy55596** [comment]
So could you make one in a future version? as there are 2 body cam versions in EUP, to make it useful for equipping vests.
